name: example of resubale workflow

on: 
 push:
   branaches:
        - main


jobs:
  reusable-deploy:
    runs-on: ubantu-latest
    steps:
      name: 
      uses: saurabhsonje/githubaction/.github/workflows/main.yml@main

